version: "3"

# Common variables
vars: {}

# Include any other Taskfiles
includes: {}

tasks:

  github-actions:
    dotenv:
      - '{{.TASKFILE_DIR}}/.env'
    vars:
      WORKFLOW_FILE: '{{ .WORKFLOW_FILE | default ".github/workflows/build-seed-image.yaml" }}'
      CONTAINER_PLATFORM: '{{.CONTAINER_PLATFORM | default .DOCKER_DEFAULT_PLATFORM }}'
    cmds:
      - cmd: >
          act
          --workflows="{{.WORKFLOW_FILE}}"
          --use-new-action-cache
          --container-architecture="{{.CONTAINER_PLATFORM}}"

  alpine-qemu-setup:
    dir: '{{ .TASKFILE_DIR }}/src/os/alpine'
    env:
      SEED_FILE_NAME: '{{ .SEED_FILE_NAME | default "alpine-seed.img" }}'
      VM_NAME: '{{.VM_NAME | default "alpine-vm" }}'
    cmds:
      - defer: |
          rm "${SEED_FILE_NAME}"
          rm "${VM_NAME}.qcow2"
          rm "${VM_NAME}.sh"
      - cmd: |
          rm "${SEED_FILE_NAME}"
          rm "${VM_NAME}.qcow2"
          rm "${VM_NAME}.sh"
        ignore_error: true
      - cmd: mkisofs -output "${SEED_FILE_NAME}" -volid CIDATA -joliet -rock user-data meta-data
      - cmd: |
          set -e
          set -x
          . ./alpine-qemu-setup.sh
