name: "Run QEMU VM build and tests"
description: "Run standardized QEMU VM build, then test with a clean setup"

inputs:
  os:
    description: The name of the OS to build and test
    required: true
    default: alpine
    type: choice
    options:
      - alpine
      # - debian # TODO
  arch:
    description: The architecture to build and test
    required: true
    default: x86_64
    type: choice
    options:
      - x86_64
      - aarch64

runs:
  using: "composite"

  steps:
    - name: Install dependencies
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y genisoimage qemu-system

    - name: Build seed image
      shell: bash
      working-directory: src/os/${{ inputs.os }}
      run: |
        set -e
        set -x
        
        # Build the seed image using mkisofs
        echo "Building cloud-init seed image..."
        mkisofs -output "${{ inputs.os }}-seed.img" -volid CIDATA -joliet -rock user-data meta-data
        
        # Verify the seed image was created
        if [ -f "${{ inputs.os }}-seed.img" ]; then
          echo "✅ SUCCESS: Seed image created"
          ls -la "${{ inputs.os }}-seed.img"
        else
          echo "❌ FAILURE: Seed image not created"
          exit 1
        fi

    - name: Test ${{ inputs.os }} ${{ inputs.arch }} QEMU VM Boot
      shell: bash
      working-directory: src/os/${{ inputs.os }}
      run: |
        set -e
        set -x
        
        # Test the qemu-setup.sh script
        echo "Testing ${{ inputs.os }} QEMU VM boot process..."
        
        # Run the script - VM will auto-shutdown via cloud-init
        ARCH=${{ inputs.arch }} . ./${{ inputs.os }}-qemu-setup.sh || echo "VM setup completed"
        
        # Verify VM files were created
        echo "Checking created VM files..."
        ls -la ${{ inputs.os }}-vm* || echo "VM files check completed"
        
        # Verify that the VM setup completed successfully
        echo "Verifying VM setup completion..."
        if [ -f "${{ inputs.os }}-vm.sh" ]; then
          echo "✅ SUCCESS: ${{ inputs.os }} QEMU VM setup completed successfully"
        else
          echo "❌ FAILURE: ${{ inputs.os }}-vm.sh runtime script not created"
          exit 1
        fi
        


    # Reference: https://github.com/actions/upload-artifact/tree/v4
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      if: env.ACT != 'true'
      with:
        name: ${{ inputs.os }}-${{ inputs.arch }}-build-artifacts
        path: |
          src/os/${{ inputs.os }}/${{ inputs.os }}-seed.img
          src/os/${{ inputs.os }}/${{ inputs.os }}-qemu-setup.sh
        retention-days: 1

