name: Build and Test Alpine QEMU VM

# Use with act:
# > act --workflows .github/workflows/build-seed-image.yaml --no-cache-server
#
# Use with task:
# > task github-actions

on:
  push:
    tags:
      - "v*.*.*"
    branches:
      - main
  # schedule:
  #   # - cron: "0 12 * * 1,3,5" # 12 PM UTC daily on Monday, Wednesday and Friday
  #   - cron: "0 12 15 * *" # 12 PM UTC on the 15th day of every month
  workflow_dispatch:
    inputs: {}

concurrency:
  # Use a unique group per workflow & branch to restrict concurrent runs
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

permissions:
  contents: write

jobs:
  Build-and-Test-Alpine-VM:
    name: Build and Test Alpine VM (${{ matrix.os }} - ${{ matrix.arch }})
    runs-on: ubuntu-latest
    timeout-minutes: 5
    strategy:
      matrix:
        os:
        - alpine
        # - debian # TODO
        arch:
        - x86_64
        - aarch64
    steps:
      # Reference: https://github.com/actions/checkout/tree/v4/
      - uses: actions/checkout@v4
        name: Checkout code

      - uses: ./.github/actions/qemu-build-and-test
        name: Build and test
        with:
          os: ${{ matrix.os }}
          arch: ${{ matrix.arch }}

      # Publish seed image as build artifacts
      # Reference: https://github.com/softprops/action-gh-release/tree/v2
      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/') && env.ACT != 'true'
        with:
          files: |
            src/os/${{ matrix.os }}/${{ matrix.os }}-seed.img
            src/os/${{ matrix.os }}/${{ matrix.os }}-qemu-setup.sh

# --------------------------------------------

# GitHub Actions Cheat Sheet: https://github.github.com/actions-cheat-sheet/actions-cheat-sheet.html
# GitHub Actions Guides: https://docs.github.com/en/actions/guides