name: Build Cloud Init Seed Image

# Use with act:
# > act --workflows .github/workflows/build-seed-image.yaml --no-cache-server
#
# Use with task:
# > task github-actions

on:
  push:
    tags:
      - "v*.*.*"
    branches:
      - main
    paths:
    - "user-data.yaml"
    - "meta-data.yaml"
  # schedule:
  #   # - cron: "0 12 * * 1,3,5" # 12 PM UTC daily on Monday, Wednesday and Friday
  #   - cron: "0 12 15 * *" # 12 PM UTC on the 15th day of every month
  workflow_dispatch:
    inputs: {}

concurrency:
  # Use a unique group per workflow & branch to restrict concurrent runs
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

env:
  SEED_FILE_NAME: cloud-init-seed.img

jobs:
  Build-and-Release-Files:
    name: Build And Release Files
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      # Reference: https://github.com/actions/checkout/tree/v4/
      - uses: actions/checkout@v4
        name: Checkout code

      - name: Install genisoimage
        # GitHub Actions Runner Resource Limits:
        # https://docs.github.com/en/actions/using-github-hosted-runners/using-github-hosted-runners/about-github-hosted-runners#standard-github-hosted-runners-for--private-repositories
        run: |
          sudo apt-get update
          sudo apt-get install -y genisoimage

      - name: Build Seed-Image
        run: |
          mkisofs -output "${{ env.SEED_FILE_NAME }}" -volid CIDATA -joliet -rock user-data meta-data

      # Reference: https://github.com/actions/upload-artifact/tree/v4
      - name: Upload seed image as artifact
        uses: actions/upload-artifact@v4
        with:
          name: seed-image
          path: |
            ${{ env.SEED_FILE_NAME }}
            alpine-qemu-setup.sh
          retention-days: 1

  Test-Qemu-VM:
    name: Test Qemu VM
    runs-on: ubuntu-latest
    timeout-minutes: 30
    needs: Build-and-Release-Files
    steps:
      - name: Install QEMU
        run: |
          sudo apt-get update
          sudo apt-get install -y qemu-system

      # Reference: https://github.com/actions/download-artifact/tree/v4
      - uses: actions/download-artifact@v4
        with:
          name: seed-image
          path: ./

      - name: Run Setup Script
        run: |
          chmod u+x ./alpine-qemu-setup.sh
          ./alpine-qemu-setup.sh

      - name: Confirm that the file "./alpine-qemu.sh" is created
        run: |
          if [ -f "./alpine-qemu.sh" ]; then
            echo "File exists"
          else
            echo "File does not exist"
            exit 1
          fi

  Publish-Files:
    name: Publish release files
    runs-on: ubuntu-latest
    timeout-minutes: 5
    needs: Test-Qemu-VM
    steps:

      # Copy files "alpine-qemu-setup.sh" and "${{ env.SEED_FILE_NAME }}" from previous job
      # <HELP ME HERE>

      # Publish seed.img as build artifacts
      # Reference: https://github.com/softprops/action-gh-release/tree/v2
      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/') && env.ACT != 'true'
        with:
          files: |
            ${{ env.SEED_FILE_NAME }}
            alpine-qemu-setup.sh

# --------------------------------------------

# GitHub Actions Cheat Sheet: https://github.github.com/actions-cheat-sheet/actions-cheat-sheet.html
